version: "3.3"

services:
  webapp:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: ../containers/webapp/Dockerfile
    ports:
      - "${WEB_PORT}:80"
  db:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/db/*.sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  api:
    restart: on-failure
    build: ./containers/api/
    ports:
      - "${API_PORT}:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}"

volumes:
  db-data:
